### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by pavelkouril** [MangoSister/SPHFluid#1]
Hello!

I like your project, but it is missing a license file, which means I cannot legally use it for anything. :(

Under which license is your project? Could you please specify it? :)

**Comment by MangoSister** [comment]
Hi Pavel, I've added a MIT license to it. Here you go ;) (I actually didn't expect anyone would use it.) 
As a side note, the project is created using an earlier version of Unity, still 5.X though.

**Comment by pavelkouril** [comment]
Thanks!

Well, I'm not still sure if I'll use it as a whole, just parts of it, or nothing at all; I want to use SPH for soil, as described in "Animating sand as a fluid" from SIGGRAPH 2005, so having at some base to see how SPH in Unity is done is really nice, at least for study purposes -- also this is the only functional Marching Cubes GPU implementation I've seen for Unity so far, so good job with that too!

**Comment by MangoSister** [comment]
Using SPH for soil sounds like an interesting idea. I'll probably check it out some time. Good luck!
